language: php
php:
  - 5.5
  - 5.4
services:
  - elasticsearch
before_install:
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "zend_extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - curl -L https://raw.github.com/shift31/Vaprobash/hostbase/scripts/couchbase.sh | sh
  - cbes-config.sh
install:
  - composer install --prefer-source --no-interaction --dev
script:
  - vendor/bin/phpunit